define({
  GET: {
    customerLeases: [{
	ControlRecordSystemId: "253829998",
	FilerBusinessEntityID: "C00000001",
	LeaseNumber: "X1234",
	UnitNumber: 1234,
	RequestStatus: "P",
	RequestAction: "",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "Test GLO Comment",
	CustomerComment: "Test Customer Comment"
},
{
	ControlRecordSystemId: "253829999",
	FilerBusinessEntityID: "C00000002",
	LeaseNumber: "X5678",
	UnitNumber: 2345,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829100",
	FilerBusinessEntityID: "C00000003",
	LeaseNumber: "X1111",
	UnitNumber: 3456,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829101",
	FilerBusinessEntityID: "C00000004",
	LeaseNumber: "X2222",
	UnitNumber: 4567,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829102",
	FilerBusinessEntityID: "C00000005",
	LeaseNumber: "X3333",
	UnitNumber: 5678,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829103",
	FilerBusinessEntityID: "C00000006",
	LeaseNumber: "X4444",
	UnitNumber: 6780,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829104",
	FilerBusinessEntityID: "C00000007",
	LeaseNumber: "X1111",
	UnitNumber: 3456,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829105",
	FilerBusinessEntityID: "C00000008",
	LeaseNumber: "X2222",
	UnitNumber: 4567,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829106",
	FilerBusinessEntityID: "C00000009",
	LeaseNumber: "X3333",
	UnitNumber: 5678,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829107",
	FilerBusinessEntityID: "C00000010",
	LeaseNumber: "X4444",
	UnitNumber: 6780,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829108",
	FilerBusinessEntityID: "C00000011",
	LeaseNumber: "X4444",
	UnitNumber: 6780,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: "253829109",
	FilerBusinessEntityID: "C00000012",
	LeaseNumber: "X1111",
	UnitNumber: 3456,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: 253862044,
	FilerBusinessEntityID: "C000002398",
	LeaseNumber: "114317",
	UnitNumber: 4567,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: 253862043,
	FilerBusinessEntityID: "C000002398",
	LeaseNumber: "114318",
	UnitNumber: 5678,
	RequestStatus: "P",
	RequestAction: "Pending Add",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: 253847453,
	FilerBusinessEntityID: "C000002398",
	LeaseNumber: "111757",
	UnitNumber: 6780,
	RequestStatus: "P",
	RequestAction: "Pending Delete",
	RecordStatus: "Reporting",
	District: 06,
	RRCNumber: 096330,
	DistrictAndRRCNumber: "06-096330",
	PermitNumber: "",
	FilingFrequency: "FillingFrequency",
	LeaseType: "Gas",
	PropertyAlias: "",
	RecordType: "GLO2",
	BusinessRole: "Operator",
	ReportsExpected: 1,
	EffectivePYM: 201104,
	SuspendToPYM: "",
	SuspendFromPYM: "",
	GLOComment: "",
	CustomerComment: ""
},
{
	ControlRecordSystemId: 253843522,
	FilerBusinessEntityID: "C000009222",
	LeaseNumber: "MF110844",
	UnitNumber: 1119,
	RequestStatus: "P",
	RequestAction: "Pending Update",
	RecordStatus: "***TEST***",
	District: 06,
	RRCNumber: 096339,
	PermitNumber: 10,
	FilingFrequency: "Q",
	LeaseType: "Gas9",
	PropertyAlias: 9,
	RecordType: "GLO2",
	BusinessRole: "Operator9",
	ReportsExpected: 19,
	EffectivePYM: 2011049,
	SuspendToPYM: "09/09/2009",
	SuspendFromPYM: "09/09/2009",
	GLOComment: "Test9GLO",
	CustomerComment: "Test9C"
},
]
  }
});